import { Project } from '../interfaces';

export const myProjects: Project[] = [
  {
    name: 'projectNestCourtReservation.name',
    techStach: 'projectNestCourtReservation.techStack',
    description: 'projectNestCourtReservation.description',
    thumbnailUrl: '/assets/images/projects/FirstNestJS.png',
    liveLink: 'https://kortymm.onrender.com/',
    isActive: true,
    codeLink: 'https://github.com/dao0dao/firstNestJs',
  },
  {
    name: 'projectTournament.name',
    techStach: 'projectTournament.techStack',
    description: 'projectTournament.description',
    thumbnailUrl: '/assets/images/projects/tournamentRegistration.png',
    liveLink: 'https://dao0dao.github.io/tournamentRegistration/',
    isActive: true,
    codeLink: 'https://github.com/dao0dao/tournamentRegistration',
  },
  {
    name: 'projectHomePageV1.name',
    techStach: 'projectHomePageV1.techStack',
    description: 'projectHomePageV1.description',
    thumbnailUrl: '/assets/images/projects/HomepageV1.png',
    liveLink: 'https://dao0dao.github.io/dao/',
    isActive: true,
    codeLink: 'https://github.com/dao0dao/dao',
  },
  {
    name: 'projectReservationSystem.name',
    techStach: 'projectReservationSystem.techStack',
    description: 'projectReservationSystem.description',
    thumbnailUrl: '/assets/images/projects/dailyShceduleAngular.png',
    liveLink: 'https://dao0dao.github.io/DaylyTimeline/',
    isActive: true,
    codeLink: 'https://github.com/dao0dao/DaylyTimeline',
  },
  {
    name: 'projectClubGo.name',
    techStach: 'projectClubGo.techStack',
    description: 'projectClubGo.description',
    thumbnailUrl: '/assets/images/projects/GoAkaiRYuu.png',
    liveLink: 'http://torun.go.art.pl/index.html',
    isActive: true,
    codeLink: '',
  },
  {
    name: 'projectShop.name',
    techStach: 'projectShop.techStack',
    description: 'projectShop.description',
    thumbnailUrl: '/assets/images/projects/myFirstNodeJs.png',
    liveLink: 'https://my-first-node-js-shop.herokuapp.com/',
    isActive: false,
    codeLink: 'https://github.com/dao0dao/nodeJsShop',
  },
  {
    name: 'projectAngularBlog.name',
    techStach: 'projectAngularBlog.techStack',
    description: 'projectAngularBlog.description',
    thumbnailUrl: '/assets/images/projects/BlogAnguralApiFirebase.png',
    liveLink: 'https://angular-forum-4489d.web.app/',
    isActive: true,
    codeLink: 'https://github.com/dao0dao/Blog-Angular',
  },
  {
    name: 'projectAngularRouting.name',
    techStach: 'projectAngularRouting.techStack',
    description: 'projectAngularRouting.description',
    thumbnailUrl: '/assets/images/projects/ForumAngularSpa.png',
    liveLink: 'https://dao0dao.github.io/AngularRoutingWithSPA',
    isActive: true,
    codeLink: 'https://github.com/dao0dao/AngularRoutingWithSPA',
  },
  {
    name: 'projectToDO.name',
    techStach: 'projectToDO.techStack',
    description: 'projectToDO.description',
    thumbnailUrl: '/assets/images/projects/ToDoAngularMaterialSpa.png',
    codeLink: 'https://github.com/dao0dao/AngularToDo',
    isActive: true,
    liveLink: 'https://dao0dao.github.io/AngularToDo/',
  },
  {
    name: 'projectWeatherApp.name',
    techStach: 'projectWeatherApp.techStack',
    description: 'projectWeatherApp.description',
    thumbnailUrl: '/assets/images/projects/WeatherApp.png',
    liveLink: 'https://dao0dao.github.io/WeatherApp/',
    isActive: true,
    codeLink: 'https://github.com/dao0dao/WeatherApp',
  },
  {
    name: 'projectWebsite.name',
    techStach: 'projectWebsite.techStack',
    description: 'projectWebsite.description',
    thumbnailUrl: '/assets/images/projects/WebpageFake.png',
    liveLink: 'https://dao0dao.github.io/Onepage/',
    isActive: true,
    codeLink: 'https://github.com/dao0dao/Onepage',
  },
];
